### ISSUE TITLE
Where is broker port number 8883 specified for a session?

### ISSUE THREAD

**Issue by yujingwu** [artikcloud/tutorial-mqtt-js-sample#1]
Is the following set port number to 8883?
 var client  = mqtt.connect('mqtts://api.artik.cloud', credentials);

**Comment by jonathanpaek** [comment]
yes - client implicitly sets to secure port 8883 per [IANA Standard](http://www.iana.org/) with 'mqtts://api.artik.cloud' as parameter when calling _mqtt.connect_
